function Character(Nome,Equipe,Descrição,Aparições,img,poder) {
    this.nome = Nome;
    this.equipe = Equipe;
    this.desc = Descrição;
    this.Refs = Aparições;
    this.Img = img
    this.poderes = poder
}

const Beenie = new Character('Beenie','Guardiões','Beenie,também chamado de Telecinese,principal superpoderoso dos guardiões.Ele é um astuto jovem que após ganhar seus poderes teve que ser maduro e racional para lidar com os problemas e as responsabilidades. Apesar disso,ele não perdeu seu lado jovem e interessado nas coisas ao seu redor,principalmente seu poder.',['Guardiões'],'Guardioes.png',['Telecinese','Super-Força','Conjuração de raios de energia','Voo rápido','????']);
const Kerry = new Character('Kerry','Guardiões','Kerry,Após ter sua vida destruída pela gangue Tineros,ele passa por uma série de perrengues,até ser acolhido por um homem misterioso,que o treina e enigmaticamente o dá o seus poderes,então,ele destroí os Tineros.Posteriormente,ele é um pseudo-participante dos Guardiões,ainda que se recuse a ter uma postura de um herói.',['Kerry,seu próprio solo.','Guardiões','Menino Resiliente'],'Kerry.png',['Força Sobrenatural','Transformar sua pele em aço']);
const Inera = new Character("Inera",'Guardiões','Inera sempre foi uma atenciosa mãe e uma amiga de Beenie.Ela é uma esperta e líder quando necessária.Depois de ser raptada,ela ganhou o poder de Fogo.',['Guardiões'],'Guardioes.png',['Manipulação do Fogo','Voo rápido']); 
const Alero = new Character("Alero",'Guardiões','Como um homem corajoso e forte,Alero é o pai de família.Ele é brincalhão,mas sério quando a hora pede.Ele absorveu o poder da eletricidade.',['Guardiões'],'Guardioes.png',['Manipulação da Eletricidade','Voo rápido']);
const MR = new Character('Larry','N/A','Larry, conhecido pela seu nome heróico Menino Resiliente, é o herói que protege a cidade de Glen. No início de sua história,ele passou por vários perrengues que consequenciaram numa cirúrgia que era incerta.No fim,Ele ganhou seus poderes.',['Menino Resiliente - Part I'],'MeninoResiliente.png',['Elasticidade de seus membros.'])
const Kevin = new Character('Kevin','Aliança Demoníaca','Uma enigmática personalidade e um assustador inimigo, Kevin é o antagonista principal aos Guardiões.Ele foi aliado de Hades e o primeiro inimigo de Beenie. Seu lado humano é uma icógnita que o Telecinese ainda queria saber.',['Guardiões'],'',['Força e Agilidade sob-humanas','Voo rápido','Conjuração de raios de energia','?????'])
const HadesTerra = new Character('Hades(Terra)','Aliança Demoníaca','Um misterioso inimigo que se demonstrou ser assustadoradamente forte, Hades, ou Demônio, é uma ameaça à terra. Ele usou sua equipe para tentar dominar o planeta,porém foi milagrosamente derrotado,porém não completamente,e em qualquer hora,ele pode voltar.',['Guardiões'],'Hades.png',['Voo rápido','Força Astronômica','Teletransporte','Agilidade astronômica','Absorver poder(Lampião)','Telecinese','Várias outras capacidades.'])
const PawFroz = new Character('Paw Froz','Aliança Demoníaca','Aparecendo primeiramente como "o idoso do mercado",Paw Froz foi um ajudante do Demônio que foi como um braço direito. Sua origem,índole e seus poderes são bem misteriosos.',['Guardiões'],'',['Manipulação do Gelo','Voo','Confecção de formas a partir do gelo'])
const Ciecon = new Character('Ciecon','Congregadores','Depois de ter ganhado seus poderes equipando o Bracelete Divino,Ciecon enfrentou o Demônio.Depois de o vencer,ele percebe que tem um poder enorme em suas mãos,e que deve usa-lo para derrotar o mal que habita pelo universo.',['Ciecon,seu próprio solo','Congregadores'],'Cong.png',['Conjuração de portais que transportam matéria.','Um subcosciente racional e Falante'])
const Rex = new Character('Rex','Congregadores','Rex é um mutante geneticamente modificado que possui algumas modificações fisiológicas que o transformam num forte combatente. Após ver toda sua espécie ser extinta de uma forma terrível,ele encontra uma salvação com seu melhor amigo,Ciecon.',['Congregadores'],'Cong.png',['Garras afiadas.','Pernas que facilitam a velocidade','Dentes longos e perfuradores.'])
const PM = new Character('Naok','Congregadores','Com uma história semelhante a de Rex,ele viu toda sua espécie,famílias,amigos sendo dizimados devido ao ataque de Delimitador e suas tropas militares.Porém,milagrosamente,ele ganhou seus poderes e derrotou o brutamonte com suas próprias mãos.',['Punho Mortal,seu próprio solo','Congregadores'],'Cong.png',['Um soco inglês que destrói tudo que é socado.'])
const Ormuz = new Character('Ormuz', 'N/A','Apesar de nunca aparecer,é o homem que criou tudo e todos,e a partir de seu poder divino, impede Hades de dominar o universo.',['Hades'],'',['Poderes Divinos e inestimados','Controle da Realidade e do espaço.','Manipulação das casualidades','Imortalidade'])
const HadesUniv = new Character('Hades(Universal)','N/A','Temido por todo o universo, Hades é a entidade divina que representa o mal. Seu poder é inestimável.Desde então,ele assumiu uma forma humana e vaga pelo universo dominando tudo pela frente,e visa possuir tudo que existe, e então, derrotar Ormuz.',['Hades,seu próprio Solo.','Ciecon'],'Hades.png',['Poderes inestimados','Imortalidade em sua forma humana','Diversas capacidades sobrenaturais de um deus.'])
const Arner = new Character('Arner','Red Right Hand','Chefe de estado e respeitado líder pelos arredores,Arner criou Severum e gerencia a Red Right Hand. Seu passado é um mistério, porém ele se importa completamente com o futuro brilhante que ele constrói.',['Red Right Hand'],'RRH.png',['Um ótimo formador de planos.','Uma intuição invejável.','????'])
const DerooDa = new Character('Deroo Da','Red Right Hand','Deroo Da é um cientista diferenciado. Com uma personalidade forte, ele se tornou um integrante da RRH quando Arner viu um potencial enorme nele. Ainda assim,ele é bem fechado e guarda pensamentos que ninguém sabe...',['Deroo Da no espaço,sua própria série','Red Right Hand','Congregadores'],'DerooDa.png',['Um conhecimento enorme sobre assuntos gerais.','Especialidade total sobre cybernética','Especialidade enorme sobre automação e veículos.','Um conhecimento gigantesco de ciências humanas','Vários outras especialidades.'])
const Delimitador = new Character('Delimitador','Red Right Hand','Um brutal mutante anatomicamente modificado para ser um forte guerreiro, porém foi consumido pelo ódio e pela ira. Depois,foi acolhido e doutrinado por Arner e se juntou a equipe.',['Red Right Hand','Punho Mortal'],'RRH.png',['Força astronômica','3 metros de altura e aproximadamente 600KG','Uma resistência sob-humana'])
const irmaos = new Character('Irmaos Yaa','Red Right Hand','Sendo uma dupla formada pelos irmãos Yaa Masin e Yaa Tsuuya, foram recrutados para a equipe quando Arner viu um grande potencial nos jovens. Eles possuem um passado triste pela perda do pai, e viram uma oportunidade de melhora de vida na equipe.',['Red Right Hand'],'RRH.png',['Uma velocidade e agilidade sob-humana','a Maldição Enokití,que dá a eles o poder de conjurar lâminas.','Os Trajes multifuncionais confeccionados para batalha.'])
const Tarlin = new Character('Tarlin','RRH / Fingers','Tarlin é um dos integrantes da RRH e líder dos Fingers. Ele sempre foi parceiro dos seus amigos da equipe,e viu uma luz quando recebeu a oferta de Arner para fazer missões na Red Right Hand. Sua personalidade é forte e ele é um sério homem quando está perto de seus "soldados"',['Red Right Hand'],'RRH.png',['Um exímio atirador,que nunca erra','Sentidos apurados','Posse do rifle Katharízo','O poder de desacelerar o tempo.'])
const Curtin = new Character('Curtin','Fingers','Sendo basicamente o vice da equipe, ele é responsável, sério, forte e um grande comparça próximo de Tarlin,que o ensinou as melhores práticas como um atirador. Ele não gosta de falar sobre seu passado.',['Red Right Hand'],'RRH.png',['Aerodinâmica invejável','turbo de seu Traje','suas pistolas Kayn & Abel'])
const Mylon = new Character('Mylon','Fingers','Antes de se juntar à equipe, ele era um bandido com fortes técnicas de combate de fogo. Tarlin,quando entrou em combate com ele, conseguiu mudar suas ideias e o tornou em um de seus soldados.',['Red Right Hand'],'RRH.png',[' Pode Controlar mentes a partir de uma luz hipnótica','Usa submetralhadoras diversas'])
const Chin = new Character('Chin','Fingers','Espontâneo e louco,porém (normalmente) obedece as ordens de Arner.Sua fascinação por explosões o torna um grande oponente.Antes de ser um Finger, ele era um guarda que cometeu acidentes e foi preso,e posteriormente foi solto por Tarlin e entrou para a equipe.',['Red Right Hand'],'RRH.png',['Chin é resistente a dores e a perfurações','Possui grandes técnicas com explosivos','Derreter,se tornando inatingível','Sua fiel metralhadora pesada'])
const Ellis = new Character('Ellis','Fingers','O novato da equipe, é quieto e introvertido, o que dificulta sua integração e amizade com o resto da equipe. Apesar disso,Tarlin vê um talento enorme no menino.',['Red Right Hand'],'RRH.png',['Especialidade em combate súbito','Camuflagem','Usa uma sniper,a Nova Owl'])
const Fingers = new Character('Fingers','','Fingers é uma equipe de soldados liderados por Tarlin, ela junta o talento de 4 jovens com a experiência do chefe para serem exímios em quaisquer ambientes ou dificuldades. Cada um deles tem trajes que levam um botão que ativam poderes selados fortíssimos e/ou úteis.',['Red Right Hand'],'RRH.png',['Exímios no combate armado','Uma Sincronia Invejável'])


export const AllCharactersTerra = [Beenie,Kerry,Inera,Alero,MR,HadesTerra,Kevin,PawFroz]
export const AllCharactersUniv = [Ormuz,HadesUniv,Ciecon,Rex,PM,Arner,DerooDa,Delimitador,irmaos,Tarlin,Curtin,Mylon,Chin,Ellis,Fingers]
export const AllCharactersFull = [Beenie,Kerry,Inera,Alero,MR,HadesTerra,Kevin,PawFroz,Ciecon,Rex,PM,Ormuz,HadesUniv,Arner,DerooDa,Delimitador,irmaos,Tarlin,Fingers,Curtin,Mylon,Chin,Ellis]