import React from 'react'

const Kerry = () => {
  return (
    <div>
      <div>
        <p><span style={{fontSize: '60pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong><em>Kerry</em></strong></span></span></span><br />
          <span style={{fontSize: '21pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong><em>O Guerreiro da Vingança.</em></strong></span></span></span></p>
        <p><span style={{fontSize: '16pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><em>UVC Solos</em></span></span></span><br />
          &nbsp;</p>
        <p><span style={{fontSize: '18pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong>1.Calamidades</strong></span></span></span></p>
        <p><span style={{fontSize: '22pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>E</span></span></span><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>m maio de 2005,Kerry era uma criança normal,que vivia na pequena cidade de Glen.Seus pais eram Kin e Clara;Ele,ia pra escola todos os dias,tirava boas notas e viviam à beira do luxo,com dinheiro provindo de empregos que eles esconder do seu filho.Ainda assim,eles eram felizes e tinham uma longa vida pela frente.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Em uma noite estrelada de sábado,a família passeava pela cidade,coisa que eles normalmente e gostavam muito de fazer.Eles estavam no carro quando o celular de Kin,vibra.Eles ignoram,para não atrapalhar o momento,mas ele não para de vibrar.Clara pega e o vê,e sussurra para Kin,de forma que&nbsp; Kerry não escutou.Eles continuam com o passeio,voltam a se divertir.Após um tempo,eles param numa estranha estrada deserta,de fato,já era tarde,mas não o suficiente para a rua estar completamente deserta.Os pais estacionam o carro,e saem,mas ordenam para Kerry não sair do carro em nenhuma circunstância;Se passou 5 minutos,nada de seus pais,então se passaram 10 minutos,e em seguida 15 minutos,sem sinal algum deles.Kerry,um menino curioso,desobedeceu seus pais e saiu,e foi lentamente espiar pela janela,mas ele com certeza não estava pronto para ver.&nbsp;</span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Ele se deparou com ambos de seus pais presos da forma mais cruel,em Pneus,banhados à álcool.Enquanto um homem os xingavam,enquanto tinha um isqueiro em sua mão.O menino desesperado,não conseguia entender direito o que eles discutiam,mas identificou que seus oaus estavan chorando e o homem,com certeza,estava os ameaçando.Ele sabia o que estava pra acontecer,mas ao mesmo tempo sabia que era incapaz de fazer algo ao mesmo tempo,ele estava numa mistura de tristeza e choque.Eram cenas fortes demais pra uma criança,mas ele sequer conseguia se mexer dali;Então ele viu seus pais serem queimados vivos.&nbsp;</span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '18pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong>2.Consequências</strong></span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Março de 2012&nbsp;</span></span></span></p>
        <p><span style={{fontSize: '22pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>K</span></span></span><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>erry se tornou um adoslecente que vivia pelas ruas de Glen.Ele praticava furtos,ele tinha uma vida fútil e sem expectativas.Mas se ele tinha um objetivo,era vingar seus amados pais.Com o tempo,ele percebeu que o homem que executou sua família fazia parte de uma gangue,ou até uma "Máfia.",os Tineros.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Num dia nublado pelas estreitas ruas de Glen,ele avista um homem,um jovem descuidado,um alvo "fácil";Ele disfarçadamente se aproximou,e tentou furtar o homem,porém,de repente,o homem saca uma faca,e vira o jogo,agora Kerry é a vítima.O homem começa a tentar acertar o jovem,que tenta desviar,mas sofria cortes das reladas que a faca fazia nos braços dele.O homem não parava de atacar,e a qualquer momento,podia machucar Kerry feio.Para a sorte do ladrão,chega um homem,também jovem,mas com uma postura mais perita que ambos.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Parem!! - Gritou o homem.Logo,Kerry se distrai e vira,o esfaqueador se aproveita,e o acerta forte com a faca na orelha de Kerry,que cai,fortemente agonizado.Rapidamente,o terceiro homem segura o esfaqueador e o&nbsp; desarma,e o rendendo.Kerry estava tão dolorido,que desmaiou.</span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '18pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong>3.Redenção</strong></span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '22pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>M</span></span></span><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>ais tarde,ele acorda,em outro lugar,diferente.Ele está todo enfaixado,e já se sente melhor,ele vê o homem que o ajudou de pé olhando para ele.&nbsp;</span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- O que você quer?! - Kerry</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Levante,garoto.Respondeu o homem.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry hesitou,mas levantou em frente ao homem.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Qual seu nome?</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Kerry.Estou na prisão?</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Era para estar.Sorte a sua que eu te salvei.Onde seus pais moram?</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry fica em silêncio</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Responda!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Eles estão mortos,#$%&amp;*!!Os Tineros queimaram eles! - Diz Kerry,triste e raivoso simultaneamente.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>O silêncio toma conta entre os dois.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Vou embora! - Diz Kerry,ainda enfurecido.Ele se vira e começa a andar para a saída.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Vá embora!Saia por essa porta e continue com essa vida vadia,roubando.Irá acabar preso ou morto.Ou fique.Fique aqui e irei lhe ensinar a lutar.Irei te ajudar a destruir os mafiosos.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Eu não ligo para o que você fala! - Diz Kerry.Que continua andando.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Perto da saída,Kerry tropeça,e cai,muito dolorido.Seus machucados começam a doer fortemente,e ele não consegue se levantar.Ele sente aquele mesmo sentimento terrível e auto-deglutidor de tristeza,incapacidade e fraqueza,e começa a chorar.O homem se aproxima dele,e estende a mão,dizendo.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Vamos,garoto.Você é melhor do que isso.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry se apoia na mão e se levanta.Ele para de chorar e escuta o homem:</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Meu nome é Luy.Vou te ensinar a lutar.&nbsp;</span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '18pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong>4. Ascensão</strong></span></span></span></p>
        <p><span style={{fontSize: '22pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>L</span></span></span><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>uy disse para Kerry o seguir,e ambos foram até uma abandonada fábrica.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Mas...Porque estamos aqui?</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Aqui é uma antiga metalúrgica.Não que importe,mas o que realmente importa é que temos espaço de sobra para nós treinarmos.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Treinar o quê?</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Irei te ensinar a como lutar como um homem.Você vai ser ágil,forte e habilidoso.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Ainda estou machucado...Como vou treinar?</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Beba isso.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Então Luy dá a Kerry uma pequena garrafa cilíndrica,Kerry ficou recioso e hesitou,mas naquele ponto era improvável ser algo ruim.Ele bebeu,e em seguida,sentiu todos os seus machucados começarem a se reconstruírem,sua pele formigar e ficar mais resistente;Ele também sente seus braços e suas pernas mais pesadas,porém a mesmo tempo maleáveis e ágeis.Ele se sentia um novo homem,completamente revigorado e pronto para aprender a lutar.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Vamos!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Curti a positividade.Primeiro,você tem que aprender a dar um soco.Tente me socar.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry tenta dar um soco rápido,mas Luy segura o soco sem esforço.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Tente novamente...Faça de conta que eu sou um Tinero,bata forte!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry tenta novamente dar um soco,só que dessa vez de fato forte.Luy desvia.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Você tem que dar um soco forte mas ao&nbsp; mesmo tempo rápido.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Tente novamente.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Então ambos ficam treinando,Kerry gradualmente aprimora seus socos.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Dia seguinte.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry&nbsp; estava dormindo num "colchão" improvisado,ainda na fábrica,quando de repente,ele é banhado à água.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Que #@#!@?!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Vamos.Já é dia.Se não acordar,vai amolecer.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry levanta,e se prepara para mais um treino.Ele acorda mais preparado do que nunca,seus músculos parecem crescer deliberadamente também.&nbsp;</span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '18pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong>5. Duro como aço</strong></span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- </span></span></span><span style={{fontSize: '22pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>H</span></span></span><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>oje será um treino diferente.Defesa.Você tem que estar preparado para&nbsp; tudo.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Luy finge que vai começar a dizer alguma coisa,mas avança e tenta socar Kerry,que desvia,no reflexo.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Tem que estar preparado para tudo,e sempre estar preparado!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Luy tira de seu bolso uma pequena faca de combate.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Você tem que aprender a desarmar também.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Luy joga a faca para Kerry,e diz:</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Tente me acertar.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Isso não é perigoso?!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Tente...</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry avança e tenta acertar Luy,que desvia.Ele tenta de novo,e Luy desvia e rapidamente torce o braço de Kerry,fazendo-o soltar a faca.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Como eu faço isso?&nbsp;</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Você tem que torcer a mão pelo pulso.Assim ele não vai conseguir mover os dedos direito.Caso seja uma arma,ele também não conseguiria atirar.Tente contra mim.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Dessa vez Luy está com a faca,tentando atacar Kerry.Ele tenta atacar Kerry,que desvia,e copia a estratégia de Luy,e então desarma o mestre.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Muito bem.Vamos novamente,desta vez serei mais rápido!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Então Kerry e Luy treinam o restante do dia inteiro.</span></span></span></p>
        <p><span style={{fontSize: '16pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><em>5 dias depois.&nbsp;</em></span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '18pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong>5.A desejada vingança.</strong></span></span></span></p>
        <p><span style={{fontSize: '22pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>K</span></span></span><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>erry já estava mais forte,tinha acordado antes mesmo que Luy,e estava malhando com equipamentos improvisados.Luy acorda e decide falar com o jovem:</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Amanhã nós iremos atacar eles.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- O que?!Já?!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Sim.Soube que se não fizermos logo,podemos ter problemas.Mas antes disso...Tenho que falar de uma coisa.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Luy aponta uma arma para Kerry</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- O que é isso,cara?</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Veja</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Luy dispara,Kerry fecha seus olhos.Mas não sente nada além de um esalo em suas pernas.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- O que foi isso?! Exclama Kerry,mais confuso do que nunca.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Você é abençoado,Kerry.Você tem um Dom.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Abençoado?Se eu fosse abençoado,meus pais ainda estariam comigo!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Luy suspira,e responde:</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Você acha que é o único?Acha que é o único que tinha amor por uma vítima daquela gangue nojenta?NÃO!Mas sim,você é o único que vai quebrar a cara de cada um deles.Você é duro como aço,e forte como chumbo.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry tenta entender aquilo,mas ainda assim aquilo era enigmático para ele.Parecia surreal,mas de fato,ele tinha simplesmente barrado a bala da arma de Luy.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Eu soube que amanhã vários deles vão estar em um bar,perto de San Clon.Eu tenho um plano,conheço um pouco do lugar.Você irá distraí-los enquanto eu subitamente vou colocar dinamites na adega do bar.Então,no meu toque,você sairá e tudo virará escombros.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry não gosta muito do plano,mas basicamente não tem como negar.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Amanhã iremos agir,durma logo,Kerry.Precisará de energia</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry foi dormir,e pensou bastante,e que de fato realizaria seu objetivo.Porém,refletiu;E depois?O que será esse poder?Porque Luy me deu este poder?Mas logo,ele se arrepia, e sente que há algo errado,ele sabe disso.Logo,ele é surpreendido por Luy,com a mão em seu ombro.Dizendo que é hora da Missão.O tempo passou muito rapidamente.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Eles chegam perto do Bar,e o plano entra em ação.Silenciosamente,nocautearam os 2 guardas que estavam protegendo a porta da frente.Em seguida,Luy se move para entrar pela porta dos fundos,e Kerry se prepara.&nbsp;</span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Ele entra,e é fuzilado por olhares.Provavelmente o lugar era restrito a Tineros.Ele se dirige ao balcão e pede uma bebida qualquer.Ele sabia que o Garçom iria até a adega,e lá iria ser morto por Luy.Ele olha à sua volta,e percebe que os homem ainda o encarava e o estranharam,todos armados fortemente.Ele,começa a cada vez virar mais irado,ele vê cada um deles como homem que cavaram as covas de seus pais.O plano era ficar quieto,parado...Mas era um desafio para ele.Até que um homem ao seu lado exclama pedindo atendimento do barman,que não corresponde(pois estava morto por Luy.)então,o homem diz:</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Porque todos nessa cidade trabalham feito animais?</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Assim que Kerry escuta isso,ele se lembra de seus pais,que,escondendo dele,trabalhavam com os Tineros,e no fim de tudo,morreram torturados e queimados de fato como animais.Ele não consegue se segurar,ele tinha um sentimento contrário a aquele de Fraqueza e Incapacidade.Ele se sentia forte e poderoso,e sentia que naquele momento ele tinha que agir.Ele se levanta,e soca o homem que disse a frase.Logo,os homens apontam armas à ele e começam a atirar,porém,todas as balas eram caiam quando chocavam contra sua duríssima pele.Algumas até ricocheteiam e mataram cada os capangas.Ele matou,à socos,cada homem a partir da pura brutalidade e do ódio.Até chegar no último restante,que já tinha se rendido,amedrontado.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Porque?!Porque vocês mataram meus pais?!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Pergunte ao Luy...Ele é que fazia esses trabalhos sujos!Me deixe ir&nbsp; embo-</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry praticamente esmaga o rosto do homem antes dele terminar de falar.</span></span></span><br />
          <br />
          <span style={{fontSize: '18pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong>6.Inespreculoso</strong></span></span></span><br />
          <br />
          <span style={{fontSize: '22pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Q</span></span></span><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>uando ele achava esse ponto mais caótico,descobriu que seu único amigo,na verdade era quem ele mais odiava,quem destruiu sua vida.Ele rapidamente,tomado pelo ódio,vai até a adega,nos fundos.Luy está bebendo,sorridente.</span></span></span></p>
        <p><br />
          <span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Eu sabia que conseguiria,Kerry!Destruímos eles,haha!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry está transbordando ódio,ele rouba a garrafa,e a joga na parede.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Foi você que matou meus pais?!</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Olha,Kerry,se eles disseram isso,é mentira!!Não acredi-</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Kerry soca Luy,e dá vários socos até eles ficarem completamente destruídos.</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>Ele sai dali,e vê aquilo tudo.O bar com as paredes furadas de tiros,homens mortos,destroçados.Ele tinha a vingança que tanto queria agora.Ele saiu do bar,e se depara com um estranho carro preto luxuoso estacionado em frente ao bar ,a porta se abre,ele se prepara para lutar,esperando que seja mais um Tinero,quando escuta:</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Você é Kerry?&nbsp;</span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>ele se dá conta,que na verdade,era o prefeito em pessoa à sua frente,tudo aquilo se torna ainda mais caótico,ele fica em choque,e mal consegue responder.Mesmo assim,o prefeito continua:</span></span></span></p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>- Entendo.Olhe,não queremos problemas,conseguimos o que queríamos.Você também.Vá para beatus.Terá dinheiro,escola uma casa e uma vida boa.Mas se ficar aqui,será uma ameaça.&nbsp;</span></span></span></p>
        <p>&nbsp;</p>
        <p><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>No dia seguinte,Kerry estava indo para Beatus,ele queria mudar,ter uma vida tranquila,fingir que nada aconteceu.Ser um homem normal.Porém ele ainda tem a dúvida do que houve.E sabe,agora,que política também está envolvida nisso.Apesar disso,ele segue sua vida,agora,nova..Mas será que ele vai viver pacatamente por muito tempo?</span></span></span><br />
          <br />
          <br />
          <br />
          &nbsp;</p>
        <p><span style={{fontSize: '30pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}><strong><em>Fim</em></strong></span></span></span><span style={{fontSize: '11pt'}}><span style={{fontFamily: 'Arial'}}><span style={{color: '#000000'}}>&nbsp;</span></span></span></p>
        <p><br />
          &nbsp;</p>
      </div>
    </div>
  )
}

export default Kerry